version: "3"
services:
       customerapi:
           container_name: customerapi
           image: customerapi
           restart: always
           build: .
           ports:
             - "8093:8080"
           depends_on:
             - db
           environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customerapi
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=123456
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
       db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_DB=customerapi
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        ports:
           - '5460:5432'